language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
